---
# tasks file for role-nix
- name: Get nix stats
  ansible.builtin.stat:
    path: /nix/
  register: nix_st
- name: Install nix
  block:
  - name: Create nix temporary directory
    ansible.builtin.tempfile:
      state: directory
      suffix: nix
    register: nix_tmpdir
  - name: Download nix
    ansible.builtin.unarchive:
      dest: "{{ nix_tmpdir.path }}"
      extra_opts: [--strip-components=1]
      remote_src: yes
      src: https://releases.nixos.org/nix/nix-{{ nix_version }}/nix-{{ nix_version }}-x86_64-linux.tar.xz
  - name: Install nix
    ansible.builtin.command: "{{ nix_tmpdir.path }}/install --no-daemon"
  - name: Remove nix temporary directory
    ansible.builtin.file:
      path: "{{ nix_tmpdir.path }}"
      state: absent
    when: nix_tmpdir.path is defined
  when: nix_st.stat.isdir is not defined
- name: Enable flakes
  ansible.builtin.lineinfile:
    create: yes
    path: /etc/nix/nix.conf
    line: experimental-features =
      flakes
      nix-command
  become: yes
- name: Enable iohk binary cache
  ansible.builtin.blockinfile:
    create: yes
    path: /etc/nix/nix.conf
    block: >-
      substituters
      =
      https://cache.nixos.org
      https://hydra.iohk.io

      trusted-public-keys
      =
      cache.nixos.org-1:6NCHdD59X431o0gWypbMrAURkbJ16ZPMQFGspcDShjY=
      hydra.iohk.io:f/Ea+s+dFdN+3Y/G+FDgSq+a5NEWhJGzdjvKNGv0/EQ=
      iohk.cachix.org-1:DpRUyj7h7V830dp/i6Nti+NEO2/nhblbov/8MW7Rqoo=
  become: yes
- name: Set nix build
  ansible.builtin.set_fact:
    nix_build: "{{ ansible_env.HOME }}/.nix-profile/bin/nix build"
